### ISSUE TITLE
A question about GOP-feature-CTC-AF

### ISSUE THREAD

**Issue by Liam0620** [frank613/CTC-based-GOP#3]
![ctc-gop-af](https://github.com/user-attachments/assets/422ec0af-7215-4735-805a-93851ff2ca55)
As described in the paper, the dim of LPR should be 39 =  38 (possible substitutions errors) + 1(deletion error). 
So why in the paper it's 40?

**Comment by frank613** [comment]
Hi,

We also include the correct phoneme in the denominiator, to make sure the GOP value is always less than 0. So it 1correct + 38sub + 1del = 40.

Thanks,
XInwei

**Comment by Liam0620** [comment]
thank you
